In [2]:
import numpy as np

In [3]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [4]:
mat


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.82833394, 0.54118637, 0.59533779, 0.81143811, 0.77406395])

In [13]:
np.random.rand(5,5)

array([[0.658666  , 0.41626529, 0.07427494, 0.12407969, 0.96194408],
       [0.83394092, 0.24163773, 0.82784665, 0.02243324, 0.51624174],
       [0.19734516, 0.88405066, 0.64396246, 0.84966943, 0.95593457],
       [0.20243734, 0.16735587, 0.29513423, 0.647218  , 0.86971251],
       [0.18386128, 0.74663037, 0.85688902, 0.3122216 , 0.29420662]])

In [14]:
np.random.randn(5)

array([ 0.14839372,  0.71821008, -0.29293973,  0.40436062, -1.14126082])

In [17]:
np.random.randn(5,5)

array([[ 1.1207893 ,  1.03414427, -0.51994171,  0.72449001,  2.13765769],
       [-1.30661782, -0.38524101,  0.08090345, -0.91520546, -1.12390906],
       [-1.44888289, -1.60170061,  0.23485037, -0.83044574, -0.53049498],
       [-0.79553227, -0.47729889,  0.21058776, -0.09213553, -1.40124109],
       [-0.89831881,  1.21689125, -0.58957292, -1.26709109, -0.33585574]])

In [22]:
np.random.randint(0,100,10)

array([86, 39, 76, 26, 78, 29, 25,  6, 25, 15])

In [23]:
arr=np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arrRan=np.random.randint(0,50,10)

In [26]:
arrRan

array([ 0,  3, 13, 14, 44, 30,  7, 30, 24, 26])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arrRan.reshape(2,5)

array([[ 0,  3, 13, 14, 44],
       [30,  7, 30, 24, 26]])

In [30]:
arrRan.max()

44

In [31]:
arrRan.min()

0

In [32]:
arrRan.argmax()

4

In [35]:
shapeArr=arr.reshape(5,5)

In [36]:
shapeArr.shape

(5, 5)

In [41]:
from numpy.random import *

In [42]:
randint(3,20)

5

In [43]:
rand(3)

array([0.36769198, 0.41364091, 0.90239909])